### ISSUE TITLE
Check Style

### ISSUE THREAD

**Issue by FelixKlauke** [vicuna-io/logcheap#22]
We should add check style with google rules to test our code for style in addition to SonarQube. Wrong aligned code etc. should lead to a build error.

**Comment by geNAZt** [comment]
Whats kek style? :D

**Comment by FelixKlauke** [comment]
https://github.com/CloudNetService/CloudNet-v3/blob/master/cloudnet-common/src/main/java/de/dytanic/cloudnet/common/Value.java - That's what they call kek style.

**Comment by merlinosayimwen** [comment]
Checkstyle doesnt really work that well with our formatting style.
